menu:
#- {name: 'people', url: '/people'}
- {name: 'projects', url: '/projects'}
- {name: 'courses', url: '/courses'}
- {name: 'cv', url: '/cv'}
- {name: 'contact', url: '/contact'}

people:
- {name: 'Primary Investigator', title: 'Researcher', department: 'Physics & Astronomy', institution: 'Some University', institution_address: '1 Main Street, Canada', phone: '(000) 000-0000', email: 'hello@university.edu', office: 'Science Building 505', image: 'assets/img/primary-investigator.jpg', url: 'primary-investigator'}
- {name: 'Lab Technician', title: 'Researcher', department: 'Physics & Astronomy', institution: 'Some University', institution_address: '1 Main Street, Canada', phone: '(000) 000-0000', email: 'hello@university.edu', office: 'Science Building 505', image: 'assets/img/lab-technician.jpg', url: 'lab-technician'}
- {name: 'Graduate Student', title: 'Researcher', department: 'Physics & Astronomy', institution: 'Some University', institution_address: '1 Main Street, Canada', phone: '(000) 000-0000', email: 'hello@university.edu', office: 'Science Building 505', image: 'assets/img/graduate-student.jpg', url: 'graduate-student'}

courses:
- {name: 'MAT157 - Analysis I', url: 'https://artsci.calendar.utoronto.ca/course/mat157y1'}
- {name: 'MAT223 - Linear Algebra I', url: 'https://artsci.calendar.utoronto.ca/course/mat223h1'}
- {name: 'MAT224 - Linear Algebra II', url: 'https://artsci.calendar.utoronto.ca/course/mat224h1'}
- {name: 'PHY151 - Foundations of Physics I', url: 'https://artsci.calendar.utoronto.ca/course/phy151h1'}
- {name: 'PHY152 - Foundations of Physics II', url: 'https://artsci.calendar.utoronto.ca/course/phy152h1'}
- {name: 'CSC148 - Introduction to Computer Science', url: 'https://artsci.calendar.utoronto.ca/course/csc148h1'}
- {name: 'CSC165 - Mathematical Expression and Reasoning for Computer Science)', url: 'https://artsci.calendar.utoronto.ca/course/csc165h1'}
- {name: 'POL107 - What Went Wrong? A Post Mortem of Political Disasters, Catastrophic Policy Failures, and Epic Marches of Folly', url: 'https://artsci.calendar.utoronto.ca/course/pol107h1'}
- {name: 'CLA204 - Introduction to Classical Mythology', url: 'https://artsci.calendar.utoronto.ca/course/cla204h1'}

social:
- {icon: 'github', link: 'https://github.com/gooosexe'}
- {icon: 'instagram', link: 'https://instagram.com/gooosexe'}
- {icon: 'linkedin', link: 'https://www.linkedin.com/in/oliver-huang-931947232/'}

contacts:
- {name: 'Oliver Huang', title: 'Undergraduate Student', department: 'Mathematical and Physical Sciences', institution: 'University of Toronto', institution_address: "27 King's College Circle, M5S1A1", phone: '(647) 615-8590', email: 'oli.huang@mail.utoronto.ca', image: 'assets/img/contact.jpeg'}
