menu:
#- {name: 'people', url: '/people'}
- {name: 'projects', url: '/projects'}
- {name: 'courses', url: '/courses'}
# - {name: 'blog', url: '/blog'}
# - {name: 'cv', url: '/cv'}
- {name: 'contact', url: '/contact'}

people:
- {name: 'Primary Investigator', title: 'Researcher', department: 'Physics & Astronomy', institution: 'Some University', institution_address: '1 Main Street, Canada', phone: '(000) 000-0000', email: 'hello@university.edu', office: 'Science Building 505', image: 'assets/img/primary-investigator.jpg', url: 'primary-investigator'}
- {name: 'Lab Technician', title: 'Researcher', department: 'Physics & Astronomy', institution: 'Some University', institution_address: '1 Main Street, Canada', phone: '(000) 000-0000', email: 'hello@university.edu', office: 'Science Building 505', image: 'assets/img/lab-technician.jpg', url: 'lab-technician'}
- {name: 'Graduate Student', title: 'Researcher', department: 'Physics & Astronomy', institution: 'Some University', institution_address: '1 Main Street, Canada', phone: '(000) 000-0000', email: 'hello@university.edu', office: 'Science Building 505', image: 'assets/img/graduate-student.jpg', url: 'graduate-student'}

courses:
- {name: 'MAT157 - analysis I', url: 'https://artsci.calendar.utoronto.ca/course/mat157y1'}
- {name: 'MAT223 - linear algebra I', url: 'https://artsci.calendar.utoronto.ca/course/mat223h1'}
- {name: 'MAT224 - linear algebra II', url: 'https://artsci.calendar.utoronto.ca/course/mat224h1'}
- {name: 'PHY151 - foundations of physics I', url: 'https://artsci.calendar.utoronto.ca/course/phy151h1'}
- {name: 'PHY152 - foundations of physics II', url: 'https://artsci.calendar.utoronto.ca/course/phy152h1'}
- {name: 'CSC148 - introduction to computer science', url: 'https://artsci.calendar.utoronto.ca/course/csc148h1'}
- {name: 'CSC165 - mathematical expression and reasoning for computer science', url: 'https://artsci.calendar.utoronto.ca/course/csc165h1'}

social:
- {icon: 'github', link: 'https://github.com/gooosexe'}
- {icon: 'instagram', link: 'https://www.instagram.com/gooose_exe/'}
- {icon: 'linkedin', link: 'https://www.linkedin.com/in/oliver-huang-931947232/'}

contacts:
- {name: 'oliver huang', title: 'undergrad student', department: 'mathematical and physical sciences', institution: 'u of t, woodsworth college', institution_address: "321 bloor street west", phone: '(647) 615-8590', school-email: 'oli.huang@mail.utoronto.ca', work-email: 'ohuang4131@gmail.com', image: 'assets/img/contact.jpeg'}
